'''Generate MAVSpec-compatible Rust messages and allocation-free MAVLink framing.

Generated payload types use MAVSpec's public derive/spec interfaces; framing is
kept separate so routers can edit targets and signatures without decoding fields.
'''
import xml.etree.ElementTree as ET
import re
import json
import copy
import shutil
from pathlib import Path

from . import mavparse


KEYWORDS = set(('abstract as async await become box break const continue crate do dyn else enum extern false '
                'final fn for gen if impl in let loop macro match mod move mut override priv pub ref return '
                'self Self static struct super trait true try type typeof union unsafe unsized use virtual '
                'where while yield TryFrom').split())
TYPES = {'char': 'u8', 'uint8_t': 'u8', 'int8_t': 'i8', 'uint16_t': 'u16', 'int16_t': 'i16',
         'uint32_t': 'u32', 'int32_t': 'i32', 'uint64_t': 'u64', 'int64_t': 'i64',
         'float': 'f32', 'double': 'f64'}


def words(name):
    # Match heck (MAVSpec)'s acronym and lower/upper word boundaries.
    name = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    name = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name)
    return re.findall(r'[a-zA-Z0-9]+', name)


def valid(name):
    if name in KEYWORDS:
        name += '_'
    if not name or name[0].isdigit():
        name = '_' + name
    return name


def snake(name):
    return valid('_'.join(w.lower() for w in words(name)))


def camel(name):
    return valid(''.join(w[0].upper() + w[1:].lower() for w in words(name)))


def enum_entries(enum):
    return [e for e in enum.entry if not e.end_marker]


def enum_type(enum):
    entries = enum_entries(enum)
    if not entries:
        raise ValueError('Rust enum %s has no entries' % enum.name)
    maximum = max(e.value for e in entries)
    if min(e.value for e in entries) < 0 or maximum >= 2**64:
        raise ValueError('Rust enum %s is outside unsigned 64-bit range' % enum.name)
    return next('u%d' % bits for bits in (8, 16, 32, 64) if maximum < 2**bits)


def entry_name(enum, entry):
    name = entry.name
    if name.startswith(enum.name + '_'):
        name = name[len(enum.name) + 1:]
    # MAVSpec's compatibility spelling for an otherwise colliding identifier.
    if entry.name == 'UAVIONIX_ADSB_NIC_CR_7_5_M':
        name = 'UAVIONIX_ADSB_NIC_CR_7_AND_5_M'
    return valid(name) if enum.bitmask else camel(name)


def doc(text):
    # XML descriptions contain indented prose, not executable Rust examples.
    return '#[cfg_attr(not(doctest), doc = %s)]\n' % json.dumps(text.strip(), ensure_ascii=False) if text.strip() else ''


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('// Generated by pymavlink. Do not edit.\n' + text, encoding='utf-8')


def generate_enum(enum):
    name, representation = camel(enum.name), enum_type(enum)
    entries = enum_entries(enum)
    names = [entry_name(enum, e) for e in entries]
    if len(set(names)) != len(names):
        raise ValueError('Rust enum name collision in ' + enum.name)
    if not enum.bitmask and len({e.value for e in entries}) != len(entries):
        raise ValueError('Rust enum %s has duplicate discriminants' % enum.name)
    out = doc(enum.description)
    if enum.bitmask:
        out += '#[derive(Copy, Clone, Debug, Default, PartialEq)]\n'
        out += '#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]\n'
        out += 'pub struct %s(%s);\n' % (name, representation)
        out += 'mavspec::rust::spec::bitflags::bitflags! { impl %s: %s {\n' % (name, representation)
        for e in entries:
            out += doc(e.description) + 'const %s = %d;\n' % (entry_name(enum, e), e.value)
        return out + '} }\n'
    out += '#[derive(mavspec::rust::derive::Enum, Copy, Clone, Debug, Default, PartialEq)]\n'
    out += '#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]\n'
    out += '#[repr(%s)]\npub enum %s {\n' % (representation, name)
    for i, e in enumerate(entries):
        out += doc(e.description)
        out += ('#[default]\n' if i == 0 else '') + '%s = %d,\n' % (entry_name(enum, e), e.value)
    return out + '}\n'


def generate_message(msg, enums):
    out = 'use mavspec::rust::spec::{MessageInfo, MessageSpec};\n'
    out += 'pub const MESSAGE_ID: u32 = %d;\npub const CRC_EXTRA: u8 = %d;\n' % (msg.id, msg.crc_extra)
    out += 'pub const MESSAGE_INFO: MessageInfo = MessageInfo::new(MESSAGE_ID, CRC_EXTRA);\n'
    out += 'pub const fn spec() -> &\'static dyn MessageSpec { &MESSAGE_INFO }\n'
    out += doc(msg.description)
    out += '#[derive(mavspec::rust::derive::Message, Clone, Debug, PartialEq)]\n'
    out += '#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]\n'
    out += '#[message_id(%d)]\n#[crc_extra(%d)]\npub struct %s {\n' % (msg.id, msg.crc_extra, camel(msg.name))
    for i, field in enumerate(msg.fields):
        out += doc(field.description)
        typ = TYPES[field.type]
        if field.enum:
            enum = enums[field.enum]
            out += '#[base_type(%s)]\n' % typ
            # Some current XML fields store only the low bits of a wider enum
            # (e.g. GIMBAL_DEVICE_INFORMATION.cap_flags). Keep the declared wire width.
            if enum_type(enum) != typ:
                out += '#[repr_type(%s)]\n' % enum_type(enum)
            if enum.bitmask:
                out += '#[bitmask]\n'
            typ = 'super::super::enums::' + camel(field.enum)
        if i >= msg.base_fields():
            out += '#[extension]\n'
        if field.array_length:
            typ = '[%s; %d]' % (typ, field.array_length)
            if field.array_length > 32:
                out += '#[cfg_attr(feature = "serde", serde(with = "serde_arrays"))]\n'
        out += 'pub %s: %s,\n' % (snake(field.name), typ)
    out += '}\n'
    out += 'impl crate::wire::WireMessage for %s { const WIRE_INFO: crate::wire::WireInfo = %s; }\n' % (camel(msg.name), wire_info(msg))
    return out


def wire_info(msg):
    target = 'None' if msg.target_system_fieldname is None else 'Some(%d)' % msg.target_system_ofs
    return 'crate::wire::WireInfo { id: %d, crc_extra: %d, min_length: %d, length: %d, target_offset: %s }' % (
        msg.id, msg.crc_extra, msg.wire_min_length, msg.wire_length, target)


def dialect_metadata(xml):
    # Match MAVInspect's derive_dialect_version/derive_dialect_id, including
    # its direct-includes-only, last-version-bearing-include precedence and
    # version-gated dialect ID inheritance. Changing these quirks here would
    # give existing MAVSpec consumers different dialect metadata.
    metadata = ET.parse(xml.filename)
    dialect_id = metadata.findtext('dialect')
    version = metadata.findtext('version')
    for include in xml.include:
        parent = ET.parse(Path(xml.filename).parent / include)
        parent_version = parent.findtext('version')
        if metadata.findtext('version') is None and parent_version is not None:
            version = parent_version
        if metadata.findtext('dialect') is None and parent_version is not None:
            dialect_id = parent.findtext('dialect')
    return dialect_id, version


def generate(basename, xml):
    if any(x.wire_protocol_version not in (mavparse.PROTOCOL_1_0, mavparse.PROTOCOL_2_0) for x in xml):
        raise ValueError('Rust supports MAVLink 1 and 2 only')
    root = Path(basename)
    root.mkdir(parents=True, exist_ok=True)
    enums = {e.name: e for x in xml for e in x.enum}
    messages = {m.id: m for x in xml for m in x.message}
    names = [snake(m.name) for m in messages.values()]
    if len(set(names)) != len(names):
        raise ValueError('Rust message name collision')
    root.joinpath('Cargo.toml').write_text('''[package]
name = "mavlink-generated"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
[features]
default = []
std = ["mavspec/std"]
serde = ["dep:serde", "dep:serde_arrays"]
[dependencies]
mavspec = { version = "0.6.7", default-features = false, features = ["rust"] }
sha2 = { version = "0.10", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
serde_arrays = { version = "0.2", default-features = false, optional = true }
''', encoding='utf-8')
    # mavparse merges enum extensions globally for C. Recover each dialect's
    # scope using entry origin files, preserving MAVSpec's distinct extended types.
    by_path = {Path(x.filename).resolve(): x for x in xml}
    for enum in enums.values():
        for entry in enum_entries(enum):
            if not entry.origin_file or Path(entry.origin_file).resolve() not in by_path:
                raise ValueError('Unknown Rust enum entry origin for ' + entry.name)
    closures = {}

    def closure(x):
        path = Path(x.filename).resolve()
        if path not in closures:
            paths = {path}
            for include in x.include:
                paths.update(closure(by_path[(path.parent / include).resolve()]))
            closures[path] = paths
        return closures[path]

    def enum_signature(enum):
        return enum.bitmask, tuple((e.name, e.value) for e in enum_entries(enum))

    def check_names(objects, label):
        for naming in (snake, camel):
            names = [naming(o.name if hasattr(o, 'name') else o.basename) for o in objects]
            if len(set(names)) != len(names):
                raise ValueError('Rust %s name collision' % label)

    check_names(xml, 'dialect')
    scopes = {}
    declarations = ''
    for x in sorted(xml, key=lambda x: len(closure(x))):
        paths = closure(x)
        scoped = {}
        for enum in enums.values():
            entries = [e for e in enum_entries(enum) if Path(e.origin_file).resolve() in paths]
            if entries:
                en = copy.copy(enum)
                en.entry = entries
                scoped[en.name] = en
        check_names(list(scoped.values()), 'enum')
        scopes[x.basename] = scoped
        parents = [p for p in xml if p.basename in scopes and p is not x
                   and Path(p.filename).resolve() in paths]
        parents.sort(key=lambda p: len(closure(p)))
        name = camel(x.basename)
        own_messages = sorted((messages[i] for i in x.message_crcs), key=lambda m: m.id)
        check_names(own_messages, 'message')
        directory = root / 'src' / 'dialects' / snake(x.basename)
        enum_declarations = ''
        for enum in scoped.values():
            parent = next((p for p in parents if enum.name in scopes[p.basename]
                           and enum_signature(enum) == enum_signature(scopes[p.basename][enum.name])), None)
            if parent is None:
                write(directory / 'enums' / (snake(enum.name) + '.rs'), generate_enum(enum))
                enum_declarations += 'pub mod %s;\n' % snake(enum.name)
            else:
                enum_declarations += 'pub use crate::dialects::%s::enums::%s;\n' % (snake(parent.basename), snake(enum.name))
            enum_declarations += 'pub use %s::%s;\n' % (snake(enum.name), camel(enum.name))
        write(directory / 'enums.rs', enum_declarations)
        message_declarations = ''
        for msg in own_messages:
            def same_enums(p):
                return all(enum_signature(scoped[f.enum]) == enum_signature(scopes[p.basename][f.enum])
                           for f in msg.fields if f.enum)
            parent = next((p for p in parents if msg.id in p.message_crcs and same_enums(p)), None)
            if parent is None:
                write(directory / 'messages' / (snake(msg.name) + '.rs'), generate_message(msg, scoped))
                message_declarations += 'pub mod %s;\n' % snake(msg.name)
            else:
                message_declarations += 'pub use crate::dialects::%s::messages::%s;\n' % (snake(parent.basename), snake(msg.name))
            message_declarations += 'pub use %s::%s;\n' % (snake(msg.name), camel(msg.name))
        write(directory / 'messages.rs', message_declarations)
        out = 'pub mod enums;\npub mod messages;\n'
        out += '#[derive(mavspec::rust::derive::Dialect, Clone, Debug, PartialEq)]\n'
        out += '#[allow(clippy::large_enum_variant)]\n'
        out += '#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]\n'
        dialect_id, version = dialect_metadata(x)
        if dialect_id is not None:
            out += '#[dialect(%d)]\n' % int(dialect_id)
        if version is not None:
            out += '#[version(%d)]\n' % int(version)
        out += 'pub enum %s {\n' % name
        for m in own_messages:
            out += '%s(messages::%s),\n' % (camel(m.name), camel(m.name))
        out += '}\n'
        for m in own_messages:
            out += 'impl From<messages::%s> for %s { fn from(value: messages::%s) -> Self { Self::%s(value) } }\n' % (camel(m.name), name, camel(m.name), camel(m.name))
        out += 'impl crate::wire::WireDialect for %s { fn wire_info(id: u32) -> Option<crate::wire::WireInfo> { match id {\n' % name
        for m in own_messages:
            out += '%d => Some(%s),\n' % (m.id, wire_info(m))
        out += '_ => None,\n} } }\n'
        write(directory / 'mod.rs', out)
        declarations += 'pub mod %s;\n' % snake(x.basename)
    write(root / 'src' / 'dialects.rs', declarations)
    write(root / 'src' / 'lib.rs', '''#![cfg_attr(not(feature = "std"), no_std)]
#![allow(rustdoc::broken_intra_doc_links, rustdoc::invalid_rust_codeblocks, rustdoc::bare_urls)]
pub mod dialects;
pub use default_dialect::{enums, messages};
pub mod wire;
pub use mavspec;
pub use mavspec::rust::spec;
''' + 'pub use dialects::%s as default_dialect;\npub use default_dialect::%s as DefaultDialect;\n' % (snake(xml[0].basename), camel(xml[0].basename)))
    shutil.copyfile(Path(__file__).parent / 'Rust' / 'wire.rs', root / 'src' / 'wire.rs')
    print('Generated Rust crate in %s (%d messages)' % (root, len(messages)))
