#!/usr/bin/env python3
"""Generate mavlink_cmd_helpers.h — per-MAV_CMD range-check tables and helpers.

Outputs a header with:
  - param_bounds[]     explicit min/max from XML minValue/maxValue attributes
  - cmd_flags_table[]  hasLocation and isDestination flags from XML
  - Helper functions: is_sentinel, lat_in_range, lon_in_range,
                      cmd_flags, has_location, is_destination, check_range

All commands with bounds or flags defined in the XML are included in the tables.
"""

import argparse
import math
import os
import sys

# Allow package-relative imports when invoked as a script.
# The grandparent of this file is the directory that contains the
# "pymavlink" package (e.g. the repo root or site-packages parent).
if __name__ == "__main__" and __package__ is None:
    _here = os.path.dirname(os.path.abspath(__file__))          # generator/
    _pymavlink = os.path.dirname(_here)                          # pymavlink/
    _root = os.path.dirname(_pymavlink)                          # <root>/
    if _root not in sys.path:
        sys.path.insert(0, _root)

from pymavlink.generator import mavparse


def load_with_includes(xml_path):
    """Parse xml_path and all transitively included files, merge enums into root."""
    base = os.path.dirname(os.path.abspath(xml_path))
    root = mavparse.MAVXML(xml_path, wire_protocol_version=mavparse.PROTOCOL_2_0)
    all_xml = [root]
    seen = {os.path.abspath(xml_path)}
    queue = [os.path.join(base, f) for f in root.include]
    while queue:
        path = os.path.abspath(queue.pop(0))
        if path in seen:
            continue
        seen.add(path)
        try:
            x = mavparse.MAVXML(path, wire_protocol_version=mavparse.PROTOCOL_2_0)
            all_xml.append(x)
            queue += [os.path.join(os.path.dirname(path), f) for f in x.include]
        except Exception:
            pass
    mavparse.merge_enums(all_xml)
    return root


def float_c(v):
    """Format a Python float as a C float literal, using NAN for nan values."""
    if math.isnan(v):
        return "(float)NAN"
    s = repr(float(v))
    # Ensure there's always a decimal point for clarity
    if "." not in s and "e" not in s:
        s += ".0"
    return s + "f"


def generate(xml_path, output_path):
    root = load_with_includes(xml_path)

    mav_cmd = next((e for e in root.enum if e.name == "MAV_CMD"), None)
    if mav_cmd is None:
        raise RuntimeError("MAV_CMD enum not found in %s" % xml_path)

    # Collect all MAV_CMD entries, sorted by cmd value
    entries = sorted(mav_cmd.entry, key=lambda e: int(e.value))

    # Build param bounds table — only params with at least one bound defined
    bounds = []  # list of (cmd, param_1based, lo_float, hi_float)
    for entry in entries:
        cmd = int(entry.value)
        for param in entry.param:
            if param.reserved:
                continue
            lo_s = (param.minValue or "").strip()
            hi_s = (param.maxValue or "").strip()
            if lo_s or hi_s:
                lo = float(lo_s) if lo_s else float("nan")
                hi = float(hi_s) if hi_s else float("nan")
                bounds.append((cmd, int(param.index), lo, hi))

    # Build cmd flags table
    flags = []  # list of (cmd, flags_byte, short_name)
    for entry in entries:
        cmd = int(entry.value)
        f = 0
        if getattr(entry, "has_location", False):
            f |= 1  # CMD_FLAG_HAS_LOCATION
        if getattr(entry, "is_destination", False):
            f |= 2  # CMD_FLAG_IS_DESTINATION
        short = entry.name.replace("MAV_CMD_", "")
        flags.append((cmd, f, short))

    with open(output_path, "w") as out:
        _write(out, bounds, flags)


_HEADER_TOP = """\
/* AUTO-GENERATED by mavgen_cmd_helpers.py from {xml} — do not edit.
 * Regenerated by the build system when the mavlink submodule or XML changes.
 */
#pragma once

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
namespace mavlink_cmd_helpers {{
#endif

/* -------------------------------------------------------------------
 * Sentinel detection
 *
 * is_sentinel(): non-zero if v means "param not provided".
 * NaN is the MAVLink standard sentinel.
 * ±0.0 is also accepted by default: many GCS tools send 0 for unused
 * fields rather than NaN.
 *
 * Define MAVLINK_CMD_STRICT_SENTINEL (e.g. -DMAVLINK_CMD_STRICT_SENTINEL
 * in a test build) to reject ±0.0 and require NaN only — useful for
 * auditing senders that send 0 instead of NaN.
 * ------------------------------------------------------------------- */
static inline int is_sentinel(float v)
{{
\tuint32_t bits;
\t__builtin_memcpy(&bits, &v, sizeof(bits));
\tif ((bits & 0x7F800000u) == 0x7F800000u) return 1; /* NaN — always a sentinel */
#ifndef MAVLINK_CMD_STRICT_SENTINEL
\tif (!(bits & 0x7FFFFFFFu)) return 1;                /* ±0.0 — default sentinel */
#endif
\treturn 0;
}}

/* is_coord_sentinel(): additionally treats INT32_MAX-derived values as
 * sentinel.  MISSION_ITEM_INT / COMMAND_INT use INT32_MAX (≈ 2.15e9
 * as float) in params 5/6 to mean "use current position". */
static inline int is_coord_sentinel(float v, bool is_int)
{{
\treturn is_sentinel(v) || (is_int && (v >= 2.0e9f || v <= -2.0e9f));
}}

/* -------------------------------------------------------------------
 * Geographic range helpers — call these directly after check_range()
 * when you know the frame is global and has_location(cmd) == 1.
 *
 * is_int=true: COMMAND_INT / MISSION_ITEM_INT — p5/p6 are int32 × 1e7.
 *   lat ∈ [−9×10⁸, 9×10⁸]   (±90°  × 1e7)
 *   lon ∈ [−1.8×10⁹, 1.8×10⁹]  (±180° × 1e7)
 * is_int=false: COMMAND_LONG — p5/p6 are float degrees.
 *   lat ∈ [−90, 90],  lon ∈ [−180, 180]
 * ------------------------------------------------------------------- */
static inline int lat_in_range(float v, bool is_int)
{{
\tif (is_coord_sentinel(v, is_int)) return 1;
\treturn is_int ? (v >= -9e8f   && v <= 9e8f)
\t             : (v >= -90.0f  && v <= 90.0f);
}}

static inline int lon_in_range(float v, bool is_int)
{{
\tif (is_coord_sentinel(v, is_int)) return 1;
\treturn is_int ? (v >= -1.8e9f  && v <= 1.8e9f)
\t             : (v >= -180.0f  && v <= 180.0f);
}}

"""

_TABLES_MID = """\

/* Per-command attribute flags from XML hasLocation / isDestination. */
struct CmdFlags {{ uint16_t cmd; uint8_t flags; }};

#define CMD_FLAG_HAS_LOCATION   (1u << 0u)
#define CMD_FLAG_IS_DESTINATION (1u << 1u)

"""

_HEADER_BOTTOM = """\

/* -------------------------------------------------------------------
 * Public helpers
 * ------------------------------------------------------------------- */

/* cmd_flags(): binary search for command attribute flags.
 * Returns the flags byte, or -1 if cmd is not in the table. */
static inline int cmd_flags(uint16_t cmd)
{{
\tunsigned lo = 0u, hi = cmd_flags_count;
\twhile (lo < hi) {{
\t\tunsigned mid = lo + (hi - lo) / 2u;
\t\tif      (cmd_flags_table[mid].cmd == cmd) return (int)cmd_flags_table[mid].flags;
\t\telse if (cmd_flags_table[mid].cmd <  cmd) lo = mid + 1u;
\t\telse                                       hi = mid;
\t}}
\treturn -1;
}}

/* has_location(): 1 if cmd carries lat/lon/alt, 0 if not, -1 if unknown. */
static inline int has_location(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_HAS_LOCATION) != 0);
}}

/* is_destination(): 1 if cmd is a waypoint destination, 0 if not, -1 if unknown. */
static inline int is_destination(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_IS_DESTINATION) != 0);
}}

/* _bound_is_set(): non-zero if v is a finite bound (not NaN / ±Inf).
 * Used internally by check_range(); bit-manipulation avoids isnan(). */
static inline int _bound_is_set(float v)
{{
\tuint32_t bits;
\t__builtin_memcpy(&bits, &v, sizeof(bits));
\treturn (bits & 0x7F800000u) != 0x7F800000u;
}}

/* check_range(): validate params 1-7 against XML-defined bounds only.
 *
 * Returns:
 *   0   all params in range (or sentinel); also returned when the command
 *       has no range data — unknown commands are accepted, not rejected.
 *   1-7 1-based index of the first param that fails a range check
 *
 * Geographic range (lat/lon) is NOT checked here — call lat_in_range() and
 * lon_in_range() separately when you know the frame is global. */
static inline int check_range(uint16_t cmd,
\tfloat p1, float p2, float p3, float p4,
\tfloat p5, float p6, float p7)
{{
\tconst float params[7] = {{p1, p2, p3, p4, p5, p6, p7}};

\t/* Binary search: find any entry for this cmd in param_bounds. */
\tunsigned lo = 0u, hi = param_bounds_count;
\twhile (lo < hi) {{
\t\tconst unsigned mid = lo + (hi - lo) / 2u;
\t\tif      (param_bounds[mid].cmd < cmd) {{ lo = mid + 1u; continue; }}
\t\telse if (param_bounds[mid].cmd > cmd) {{ hi = mid;      continue; }}
\t\t/* Found.  Back up to first entry for this cmd. */
\t\tunsigned start = mid;
\t\twhile (start > 0u && param_bounds[start - 1u].cmd == cmd) {{ --start; }}
\t\t/* Walk all entries for this cmd. */
\t\tfor (unsigned i = start;
\t\t     i < param_bounds_count && param_bounds[i].cmd == cmd; ++i) {{
\t\t\tconst unsigned pidx = (unsigned)param_bounds[i].param - 1u;
\t\t\tconst float v = params[pidx];
\t\t\tif (is_sentinel(v)) {{ continue; }}
\t\t\tif (_bound_is_set(param_bounds[i].lo) && v < param_bounds[i].lo)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t\tif (_bound_is_set(param_bounds[i].hi) && v > param_bounds[i].hi)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t}}
\t\tbreak;
\t}}

\treturn 0;
}}

#ifdef __cplusplus
}} /* namespace mavlink_cmd_helpers */
#endif
"""


def _write(out, bounds, flags):
    # We need the xml basename for the comment; use a placeholder resolved at call time.
    # Instead, just use a generic note.
    out.write(_HEADER_TOP.format(xml="common.xml (via dialect include chain)"))

    # --- param_bounds table ---
    out.write("/* Explicit param bounds from XML minValue / maxValue.\n"
              " * (float)NAN for lo or hi means that side is unbounded. */\n")
    out.write("struct ParamBound { uint16_t cmd; uint8_t param; float lo; float hi; };\n\n")
    out.write("static const struct ParamBound param_bounds[] = {\n")
    for cmd, pidx, lo, hi in bounds:
        out.write(
            "\t{{ {:5d}, {:d}, {:>14s}, {:>14s} }},\n".format(
                cmd, pidx, float_c(lo), float_c(hi)
            )
        )
    out.write("};\n")
    out.write("static const unsigned param_bounds_count =\n"
              "\tsizeof(param_bounds) / sizeof(param_bounds[0]);\n")

    out.write(_TABLES_MID.format())

    # --- cmd_flags_table ---
    out.write("static const struct CmdFlags cmd_flags_table[] = {\n")
    for cmd, f, short in flags:
        parts = []
        if f & 1:
            parts.append("CMD_FLAG_HAS_LOCATION")
        if f & 2:
            parts.append("CMD_FLAG_IS_DESTINATION")
        flag_str = " | ".join(parts) if parts else "0"
        out.write("\t{{ {:5d}, {:s} }}, /* {:s} */\n".format(cmd, flag_str, short))
    out.write("};\n")
    out.write("static const unsigned cmd_flags_count =\n"
              "\tsizeof(cmd_flags_table) / sizeof(cmd_flags_table[0]);\n")

    out.write(_HEADER_BOTTOM.format())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate MAVLink command range-check helper tables"
    )
    parser.add_argument("xml", help="Root MAVLink XML dialect file (e.g. common.xml)")
    parser.add_argument("--output", required=True, help="Output .h file path")
    args = parser.parse_args()
    generate(args.xml, args.output)
    print("Generated", args.output)
