# SOME NOTES FOR RILEY FOR LATER
# EVERY MESSAGE TYPE WILL HAVE ITS OWN PACK OR SEND FUNCTION
# populate the constants into the struct, fill the struct variables, return the bytes, pass that pointer to send function
# we can do this everywhere and not worry about all the weirdass pythonisms. There's a LOT of excess data here we don't need.

#!/usr/bin/env python
"""
parse a MAVLink protocol XML file and generate a SPIN2 implementation

Copyright Riley August 2025
Released under GNU GPL version 3 or later
"""


import os
import sys
import textwrap
from . import mavtemplate

t = mavtemplate.MAVTemplate()

def generate_preamble(outf, msgs, basename, args, xml):
    print("Generating preamble")
    print("cache check wtf")
    params = dict(xml)
    params["FILELIST"] = (",".join(args),)
    params["DIALECT"] = os.path.splitext(os.path.basename(basename))[0]

    t.write(
        outf,
        '''
{Spin2_v51}
{{
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: ${FILELIST}

Note: this file has been auto-generated. DO NOT EDIT
}}

DAT
    WIRE_PROTOCOL_VERSION    byte    "2.0"
    DIALECT            byte    "spin2"

CON
    PROTOCOL_MARKER_V1 = $FE
    PROTOCOL_MARKER_V2 = $FD
    HEADER_LEN_V1 = 6
    HEADER_LEN_V2 = 10

    MAVLINK_SIGNATURE_BLOCK_LEN = 13

    MAVLINK_IFLAG_SIGNED = $01
    MAVLINK_IFLAG_SYSID32 = $02
    MAVLINK_IFLAG_TARGET32 = $04
    LITTLE_ENDIAN = True
    PROTOCOL_MARKER = ${protocol_marker}
    MAVLINK_PAYLOAD_SIZE = 255
    MAVLINK_BUF_LEN = 287
    MAVLINK_IGNORE_CRC = True ' fix this later
    STRUCT int64(msb, lsb)
    STRUCT double(msb, lsb)
VAR    
    BYTE payload_buf [MAVLINK_PAYLOAD_SIZE]
    BYTE buf [MAVLINK_BUF_LEN]    
    BYTE sequence ' sequence number for the CURRENT SESSION
    LONG total_bytes_sent
    LONG total_packets_sent
    LONG payloadTarget
    LONG srcSystemId
    BYTE srcComponentId
    WORD expected_length
    ' long startup_time
    
' OBJ
' logger : "logger" tODO: implement normie logging
' allow MAV_IGNORE_CRC=1 to ignore CRC, allowing some
' corrupted msgs to be seen    
    
CON 
' some base types from mavlink_types.h
    MAVLINK_TYPE_CHAR = 0
    MAVLINK_TYPE_UINT8_T = 1
    MAVLINK_TYPE_INT8_T = 2
    MAVLINK_TYPE_UINT16_T = 3
    MAVLINK_TYPE_INT16_T = 4
    MAVLINK_TYPE_UINT32_T = 5
    MAVLINK_TYPE_INT32_T = 6
    MAVLINK_TYPE_UINT64_T = 7
    MAVLINK_TYPE_INT64_T = 8
    MAVLINK_TYPE_FLOAT = 9
    MAVLINK_TYPE_DOUBLE = 10

{{CRC-16/MCRF4XX - based on checksum.h from mavlink library}}

VAR 
    WORD crc
    BYTE tmp1, tmp2
    
pub get_crc():result
    result := crc
    return
    
pub make_crc(msgadr,len,CRC_EXTRA)
    crc:=$FFFF
    byte[msgadr+len-2]:= CRC_EXTRA & $FF ' stick the crcextra in the first byte
    msgadr++ ' skip first byte (protocol marker)
    repeat len-2
        crc:=metabolize(crc,byte[msgadr++])
    
pri metabolize (ccrc,databyte) : temp
    temp:=databyte
    repeat 8
       if (ccrc & 1) == (temp & 1)
         ccrc:=(ccrc & $FFFF) >> 1
         temp:=(temp & $FF) >> 1
       else
         ccrc:=(ccrc & $FFFF) >> 1
         temp:=(temp & $FF) >> 1
         ccrc:=((ccrc & $FFFF) ^ $8408) & $FFFF
    temp:=ccrc

''',
        params,
    )


def generate_enums(outf, enums):
    print("Generating enums")
    outf.write("CON")
    for e in enums:
        outf.write("\n' %s\n" % e.name) # enum category
        for entry in e.entry:
            outf.write("%s = %u\n" % (entry.name, entry.value))
            description = entry.description.replace("\t", "    ")
            outf.write("%s = %u\n" % (entry.name+"_description", description))
    return
                 
def generate_message_ids(outf, msgs):
    print("Generating message IDs")
    outf.write("\n' message IDs\n")
    outf.write("CON\n")
    outf.write("\tMSG_ID_BAD_DATA = -1\n")
    outf.write("\tMSG_ID_UNKNOWN = -2\n")
    for m in msgs:
        nm = "MSG_ID_%s" % (m.name.upper())
        if (len(nm) > 30):
            nm = "M_ID_%s" % (m.name.upper())
        if (len(nm) > 30):            
            outstr = m.name.upper().replace("_A", "_a").replace("_E","_e").replace("_I","_i").replace("_O","_o").replace("_U","_u")            
            outstr = outstr.replace("A","").replace("E","").replace("I","").replace("O","").replace("U","")            
            nm = "M_ID_%s" % (outstr.upper())
        if (len(nm) > 30):
            nm = nm[0:30]
        outf.write("\t%s = %u\n" % (nm, m.id))


def byname_hash_from_field_attribute(m, attribute):
    strings = []
    for field in m.fields:
        value = getattr(field, attribute, None)
        if value is None or value == "":
            continue
        if attribute == "units":
            # hack; remove the square brackets further up
            if value[0] == "[":
                value = value[1:-1]
        strings.append('"%s": "%s"' % (field.name, value))
    return ", ".join(strings)


def generate_message_defs(outf, msgs, enums):
    wrapper = textwrap.TextWrapper(initial_indent="", subsequent_indent="    ")
    for m in msgs:
        m.classname = "MAVLink_%s_message" % m.name.lower()        
        m.spin_fields = []
        m.spin_names = []
        m.init_fields = []
        m.cleanname = m.name.lower()
        if len(m.cleanname) > 25:
            # strip then truncate
            m.cleanname.replace("system", "sys")
            m.cleanname.replace("SYSTEM", "SYS")
            m.cleanname = m.name.upper().replace("_A", "_a").replace("_E","_e").replace("_I","_i").replace("_O","_o").replace("_U","_u")            
            m.cleanname = m.cleanname.replace("A","").replace("E","").replace("I","").replace("O","").replace("U","")
            m.cleanname = m.cleanname.lower()
        if len(m.cleanname) > 25:
            m.cleanname = m.cleanname[0:25]
        if len(m.classname) > 30:
            m.classname = "M_%s_mg" % m.cleanname
        # SPIN2 STRUCT FORMAT IS CON STRUCT struct_ name (TYPE name[array],...)    
        # var limits are 30
        # ESCAPE SPIN KEYWORDS
        for field in m.ordered_fields:                
            # TODO: CHANGE THIS TO A RESERVED DICT
            if(field.name == "sequence"):
                field.name = "_sequence"
            elif(field.name == "end"):
                field.name = "_end"
            elif(field.name == "field"):
                field.name = "_field"
            if len(field.name) > 30:
                field.name.upper().replace("SYSTEM", "SYS")
                # strip then truncate
                field.name = field.name.upper().replace("_A", "_a").replace("_E","_e").replace("_I","_i").replace("_O","_o").replace("_U","_u")            
                field.name = field.name.replace("A","").replace("E","").replace("I","").replace("O","").replace("U","")
                field.name = field.name.lower()
            if len(field.name) > 30:
                field.name = field.name[0:30]            
            if field.type == "uint8_t" or field.type == "int8_t" or field.type.startswith("char"):
                if(field.array_length > 0):
                    m.spin_names.append(field.name) # array pointer takes precedence over struct pointer, we just receive a long
                    m.spin_fields.append("BYTE " + field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_names.append(field.name)
                    m.spin_fields.append("BYTE " + field.name)
            elif field.type == "uint16_t" or field.type == "int16_t":
                if(field.array_length > 0):
                    m.spin_names.append(field.name) # array pointer takes precedence over struct pointer, we just receive a long
                    m.spin_fields.append("WORD " + field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_names.append(field.name)
                    m.spin_fields.append("WORD " + field.name)
            elif field.type == "uint32_t" or field.type == "int32_t" or field.type == "float":
                if(field.array_length > 0):
                    m.spin_names.append(field.name) # array pointer takes precedence over struct pointer, we just receive a long
                    m.spin_fields.append(field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_names.append(field.name)
                    m.spin_fields.append(field.name)
            elif field.type == "uint64_t" or field.type == "int64_t":
                if(field.array_length > 0):
                    m.spin_names.append(field.name) # array pointer takes precedence over struct pointer, we just receive a long
                    m.spin_fields.append("int64 " + field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_names.append("int64 " + field.name)
                    m.spin_fields.append("int64 " + field.name)
            elif field.type == "double":
                if(field.array_length > 0):
                    m.spin_names.append(field.name) # array pointer takes precedence over struct pointer, we just receive a long
                    m.spin_fields.append("double " + field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_names.append("double " + field.name)
                    m.spin_fields.append("double " + field.name)
                
            else:
                if field.array_length > 0:                    
                    m.spin_names.append(field.name) # I'm an array of unknown structs
                    m.spin_fields.append(field.type + field.name + "[" + str(field.array_length) + "]")
                else:
                    m.spin_fields.append(field.type + " " + field.name) # I'm an unknown struct
                    m.spin_names.append(field.type + " " + field.name)        
            if(field.array_length > 0):
                if(field.type == "double"):
                    m.init_fields.append("BYTEMOVE(@msg.%s, %s, %s*sizeof(double))" % (field.name, field.name, field.array_length))
                elif(field.type == "uint64_t" or field.type == "int64_t"):
                    m.init_fields.append("BYTEMOVE(@msg.%s, %s, %s*sizeof(int64))" % (field.name, field.name, field.array_length))
                else:
                    m.init_fields.append("BYTEMOVE(@msg.%s, %s, %s)" % (field.name, field.name, field.array_length * field.type_length))
            else:
                if field.is_target_system:
                    m.init_fields.append("if %s & $FFFFFF00\n        msg.%s := 255\n    else\n        msg.%s := %s" % (field.name, field.name, field.name, field.name))
                else:
                    m.init_fields.append("msg.%s := %s" % (field.name, field.name))
        t.write(
            outf,
            '''

{{
${docstring}
}}
CON
    ${cleanname}_id = ${msgid}
    ${cleanname}_crcx = ${crc_extra}
    STRUCT ${classname} (${spin_fields})

PUB ${cleanname}_pack(${field_names}, ^${classname} msg): siz
    BYTEFILL(@payload_buf, 0, MAVLINK_PAYLOAD_SIZE)
    payloadTarget := ${target_system}
    ${init_fields}
    ' build payload
    siz := ${wire_length}
    ${copy_payload}
    

PUB ${cleanname}_send(${field_names}): siz | ${classname} msg
    BYTEFILL(@payload_buf, 0, MAVLINK_PAYLOAD_SIZE)
    payloadTarget := ${target_system}
    ${init_fields}
    ' build payload
    siz := ${wire_length}
    ${copy_payload}
    send_mavlink(${cleanname}_id, srcSystemId, srcComponentId, ${cleanname}_crcx, siz, False)

''',
                {
                    "target_system": next((f.name for f in m.fields if f.is_target_system), "0"),
                    "wire_length": m.wire_length,
                    "copy_payload": "\n    ".join("BYTEMOVE(@payload_buf + %u, @msg.%s, %u)" % (f.wire_offset, f.name, (f.array_length or 1) * f.type_length) for f in m.ordered_fields),
                    "classname": m.classname,
                    "field_names": ", ".join(m.spin_names),
                    "docstring": wrapper.fill(m.description.strip()),
                    "cleanname": m.cleanname,
                    "crc_extra": m.crc_extra,
                    "msgid": m.id,
                    "spin_fields": ", ".join(m.spin_fields),
                    "init_fields": "\n    ".join(m.init_fields),
                },
        )


def native_mavfmt(field):
    """Work out the struct format for a type."""
    map = {
        "float": "f",
        "double": "d",
        "char": "c",
        "int8_t": "b",
        "uint8_t": "B",
        "uint8_t_mavlink_version": "v",
        "int16_t": "h",
        "uint16_t": "H",
        "int32_t": "i",
        "uint32_t": "I",
        "int64_t": "q",
        "uint64_t": "Q",
    }
    return map[field.type]


def mavfmt(field):
    """work out the struct format for a type"""
    map = {
        "float": "f",
        "double": "d",
        "char": "c",
        "int8_t": "b",
        "uint8_t": "B",
        "uint8_t_mavlink_version": "B",
        "int16_t": "h",
        "uint16_t": "H",
        "int32_t": "i",
        "uint32_t": "I",
        "int64_t": "q",
        "uint64_t": "Q",
    }

    if field.array_length:
        if field.type == "char":
            return str(field.array_length) + "s"
        return str(field.array_length) + map[field.type]
    return map[field.type]


def mavpytype(field):
    c_type_to_py = {
        "float": "float",
        "double": "float",
        "char": "bytes",
        "int8_t": "int",
        "uint8_t": "int",
        "uint8_t_mavlink_version": "int",
        "int16_t": "int",
        "uint16_t": "int",
        "int32_t": "int",
        "uint32_t": "int",
        "int64_t": "int",
        "uint64_t": "int",
    }

    if field.array_length:
        if field.type == "char":
            return "bytes"
        return "Sequence[{}]".format(c_type_to_py[field.type])
    return c_type_to_py[field.type]


def mavdefault(field):
    """returns default value for field (as string) for mavlink2 extensions"""
    if field.type == "char":
        return 'b""'
    else:
        if field.array_length == 0:
            return "0"
        else:
            return "(" + ", ".join(["0"] * field.array_length) + ")"


def generate_mavlink_parser(outf, msgs, xml):
    print("Generating MAVLink parser")
# TODO: implement a lookup dict here if we still want one.
#    t.write(
#        outf,
#        """


#mavlink_map: Dict[int, Type[MAVLink_message]] = {
#""",
#        xml,
#    )
#    for m in msgs:
#        outf.write(
#            "    MAVLINK_MSG_ID_%s: MAVLink_%s_message,\n" % (m.name.upper(), m.name.lower())
#        )
#    outf.write("}\n\n")

    t.write(
        outf,
        '''
        
        
CON struct MAVLink(BYTE magic, BYTE len, BYTE incompat_flags, BYTE compat_flags, BYTE seq, LONG sysid, BYTE compid, BYTE msgid, BYTE msgid_m, BYTE msgid_h, BYTE payload[MAVLINK_PAYLOAD_SIZE], WORD checksum, LONG target_system)

CON struct MAVLink_Signed(BYTE magic, BYTE len, BYTE incompat_flags, BYTE compat_flags, BYTE seq, BYTE sysid, BYTE compid, BYTE msgid, BYTE msgid_m, BYTE msgid_h, BYTE payload[MAVLINK_PAYLOAD_SIZE], WORD checksum, BYTE signature[13])

CON struct MAVLink_1(BYTE magic, BYTE len, BYTE seq, BYTE sysid, BYTE compid, BYTE msgid, BYTE payload[MAVLINK_PAYLOAD_SIZE], WORD checksum)


' Build wire bytes separately from the decoded packet struct. Returns 0 when
' MAVLink1 cannot represent an ID. get_send_buffer() exposes the packed bytes.
PUB pack_frame(msg_id, sys_id, comp_id, crc_extra, length, force_mavlink1): size | offset, flags, i
    flags := 0
    if force_mavlink1 && ((sys_id & $FFFFFF00) || (payloadTarget & $FFFFFF00) || (msg_id & $FFFFFF00))
        return 0
    if force_mavlink1
        length := payload_length_v1(msg_id, length)
        buf[0] := PROTOCOL_MARKER_V1
        offset := 2
    else
        buf[0] := PROTOCOL_MARKER_V2
        flags := 0
        if sys_id & $FFFFFF00
            flags |= MAVLINK_IFLAG_SYSID32
        if payloadTarget & $FFFFFF00
            flags |= MAVLINK_IFLAG_TARGET32
        buf[2] := flags
        buf[3] := 0
        offset := 4
        repeat while length > 1 && payload_buf[length - 1] == 0
            length--
    buf[1] := length
    buf[offset++] := sequence++
    buf[offset++] := sys_id
    if flags & MAVLINK_IFLAG_SYSID32
        repeat i from 1 to 3
            buf[offset++] := sys_id >> (8 * i)
    buf[offset++] := comp_id
    buf[offset++] := msg_id
    if !force_mavlink1
        buf[offset++] := msg_id >> 8
        buf[offset++] := msg_id >> 16
    if flags & MAVLINK_IFLAG_TARGET32
        repeat i from 0 to 3
            buf[offset++] := payloadTarget >> (8 * i)
    BYTEMOVE(@buf + offset, @payload_buf, length)
    size := offset + length + 2
    make_crc(@buf, size, crc_extra)
    buf[size - 2] := crc
    buf[size - 1] := crc >> 8

PUB get_send_buffer(): address
    return @buf

PUB send_mavlink(msg_id, sys_id, comp_id, crc_extra, length, force_mavlink1) | size, i
    size := pack_frame(msg_id, sys_id, comp_id, crc_extra, length, force_mavlink1)
    if size == 0
        return
    repeat i from 0 to size - 1
        sendSerial(buf[i])
    total_packets_sent++
    total_bytes_sent += size

PUB send_mavlink1(msg_id, sys_id, comp_id, length, crc_extra)
    send_mavlink(msg_id, sys_id, comp_id, crc_extra, length, TRUE)

VAR
    LONG isMavlink2
    LONG sendSerial
    LONG recvSerial
    
PUB init_session(srcSystem, srcComponent, baud, serialTxPtr, serialRxPtr)
    isMavlink2 := TRUE
    srcSystemId := srcSystem
    srcComponentId := srcComponent
    expected_length := HEADER_LEN_V1 + 2 ' not sure that's right
    sendSerial := serialTxPtr
    recvSerial := serialRxPtr
    reset_session()    
    
PUB reset_session() ' reset session stats and sequence, keep IDs
    sequence~
    total_packets_sent~
    total_bytes_sent~
    isMavlink2 := TRUE

{{parser enums}}
CON 
    PARSE_STATE_UNINIT = 0
    PARSE_STATE_IDLE = 1
    PARSE_STATE_GOT_STX = 2
    PARSE_STATE_GOT_LENGTH = 3
    PARSE_STATE_GOT_INCOMPAT_FLAGS = 4
    PARSE_STATE_GOT_COMPAT_FLAGS = 5    
    PARSE_STATE_GOT_SEQ = 6
    PARSE_STATE_GOT_SYSID = 7
    PARSE_STATE_GOT_COMPID = 8
    PARSE_STATE_GOT_MSGID1 = 9
    PARSE_STATE_GOT_MSGID2 = 10
    PARSE_STATE_GOT_MSGID3 = 11    
    PARSE_STATE_GOT_CRC1 = 12
    PARSE_STATE_GOT_CRC2 = 13
    PARSE_STATE_GOT_PAYLOAD = 14
    PARSE_STATE_GOT_SIGNATURE = 15    

VAR 
    BYTE parse_state
    MAVLink inPacket
    BYTE payloadIndex
    WORD discardRemaining
    WORD receiveIndex, receiveExpected
    BYTE receiveBuffer[MAVLINK_BUF_LEN]
    
PRI crcError()
    ' Do nothing for now. TODO: implement error handling
    return

PUB newPacket()
    parse_state := PARSE_STATE_IDLE
    BYTEFILL(@inPacket, 0, sizeof(inPacket))
    payloadIndex~
    discardRemaining~
    receiveIndex~
    receiveExpected~

PUB getPacket(): packetAddr
    packetAddr := @inPacket
    return packetAddr

PUB parse_char(c) | flags, offset, i, headerlen
    if receiveIndex == 0 && c <> PROTOCOL_MARKER_V1 && c <> PROTOCOL_MARKER_V2
        return
    if parse_state == PARSE_STATE_GOT_CRC2
        newPacket()
    receiveBuffer[receiveIndex++] := c
    parse_state := PARSE_STATE_GOT_STX
    if receiveIndex < 3
        return
    isMavlink2 := receiveBuffer[0] == PROTOCOL_MARKER_V2
    flags := 0
    headerlen := HEADER_LEN_V1
    if isMavlink2
        flags := receiveBuffer[2]
        headerlen := HEADER_LEN_V2
        if flags & MAVLINK_IFLAG_SYSID32
            headerlen += 3
        if flags & MAVLINK_IFLAG_TARGET32
            headerlen += 4
    receiveExpected := headerlen + receiveBuffer[1] + 2
    if flags & MAVLINK_IFLAG_SIGNED
        receiveExpected += MAVLINK_SIGNATURE_BLOCK_LEN
    if receiveIndex < receiveExpected
        return
    receiveIndex := 0
    ' No signing implementation: reject signed and unknown frames whole.
    if flags & $F9
        parse_state := PARSE_STATE_IDLE
        return
    BYTEFILL(@inPacket, 0, sizeof(inPacket))
    inPacket.magic := receiveBuffer[0]
    inPacket.len := receiveBuffer[1]
    inPacket.incompat_flags := flags
    offset := 2
    if isMavlink2
        inPacket.compat_flags := receiveBuffer[3]
        offset := 4
    inPacket.seq := receiveBuffer[offset++]
    inPacket.sysid := receiveBuffer[offset++]
    if flags & MAVLINK_IFLAG_SYSID32
        repeat i from 1 to 3
            inPacket.sysid |= receiveBuffer[offset++] << (i * 8)
    inPacket.compid := receiveBuffer[offset++]
    inPacket.msgid := receiveBuffer[offset++]
    if isMavlink2
        inPacket.msgid_m := receiveBuffer[offset++]
        inPacket.msgid_h := receiveBuffer[offset++]
    if flags & MAVLINK_IFLAG_TARGET32
        repeat i from 0 to 3
            inPacket.target_system |= receiveBuffer[offset++] << (i * 8)
    BYTEMOVE(@inPacket.payload, @receiveBuffer + offset, inPacket.len)
    offset += inPacket.len
    inPacket.checksum := receiveBuffer[offset] | (receiveBuffer[offset + 1] << 8)
    parse_state := PARSE_STATE_GOT_CRC2

' Full-width target accessor; pass the decoded payload target for legacy frames.
PUB get_target_system(payload_target): target
    if inPacket.incompat_flags & MAVLINK_IFLAG_TARGET32
        return inPacket.target_system
    return payload_target

' CRC must cover the actual variable-length wire header, not the packet struct.
PUB check_crc(crc_extra): valid | value, i
    value := $FFFF
    repeat i from 1 to receiveExpected - 3
        value := metabolize(value, receiveBuffer[i])
    value := metabolize(value, crc_extra)
    return value == inPacket.checksum

PUB receive() : hasPacket | b
    if parse_state == PARSE_STATE_UNINIT || parse_state == PARSE_STATE_GOT_CRC2
        newPacket()
    b := recvSerial(0):1
    repeat
        if b == -1
            return FALSE
        parse_char(b)
        if parse_state == PARSE_STATE_GOT_CRC2
            return TRUE
        if parse_state == PARSE_STATE_IDLE && discardRemaining == 0
            return FALSE
        b := recvSerial(10):1
''',
        xml,
    )

    outf.write("\nPRI payload_length_v1(msg_id, length): size\n    case msg_id\n")
    for msg in msgs:
        if msg.wire_length != msg.wire_min_length:
            outf.write("        %u: return length <# %u\n" % (msg.id, msg.wire_min_length))
    # A default arm is also needed for dialects without extension fields.
    outf.write("        other: return length\n")


def generate_methods(outf, msgs):
    print("Generating methods")

    def field_descriptions(fields):
        ret = ""
        for f in fields:
            field_info = ""
            if f.units:
                field_info += "%s " % f.units
            field_info += "(type:%s" % f.type
            if f.enum:
                field_info += ", values:%s" % f.enum
            field_info += ")"
            ret += "        %-18s        : %s %s\n" % (
                f.name,
                f.description.strip(),
                field_info,
            )
        return ret

    wrapper = textwrap.TextWrapper(initial_indent="", subsequent_indent="        ")

    for m in msgs:
        comment = "%s\n\n%s" % (wrapper.fill(m.description.strip()), field_descriptions(m.fields))

        field_names = []
        for i in range(len(m.fields)):
            f = m.fields[i]
            python_type = mavpytype(f)
            if f.omit_arg:
                field_names.append("%s: %s = %s" % (f.name, python_type, f.const_value))
            elif m.extensions_start is not None and i >= m.extensions_start:
                fdefault = m.fielddefaults[i]
                field_names.append("%s: %s = %s" % (f.name, python_type, fdefault))
            else:
                field_names.append("%s: %s" % (f.name, python_type))

        self_ret_type = " -> MAVLink_" + m.name.lower() + "_message"

        t.write(
            outf,
            '''
            {TODO: figure out if we need to generate methods using this code}
''',
                {
                    "NAMELOWER": m.name.lower(),
                    "ARG_FIELDNAMES": ", ".join(field_names),
                    "COMMENT": comment,
                    "FIELDNAMES": ", ".join(m.fieldnames),
                    "self_ret_type": self_ret_type,
                },
        )
# TODO: move all the field handling stuff out of the individual generator methods so we call it once instead of 3 times
def generate_case(outf, msgs, dialect):    
    wrapper = textwrap.TextWrapper(initial_indent="", subsequent_indent="    ")
    t.write(outf,
'''
{Spin2_v51}
{{
    MAVLink message parser object for ${DIALECT} dialect, (auto-generated by mavgen.py)
}}
OBJ
    mavlink : "${DIALECT}"    
{{
    Handles an incoming MAVLink message.
}}

PUB checkCrc(crcextra, ^mavlink.MAVLink msg): result | newcrc
    return mavlink.check_crc(crcextra)

PUB crcError()
    ' TODO: Handle CRC errors for your solution

PUB handleMessage(^mavlink.MAVLink packet) | msgid
    ' little endian
    msgid := packet.msgid_h << 16
    msgid |= packet.msgid_m << 8
    msgid |= packet.msgid
    
    ' Can't use CASE_FAST; ID values have to be within 255 of each other
    ' maybe use a compare and two CASE statements in a flight controller implementation but that is beyond the scope of pymavgen
    CASE msgid
        mavlink.MSG_ID_MANUAL_CONTROL: ' highest priority is manual control and mode messages
            hdl_manual_control(@packet)
''',{"DIALECT": dialect}, )
    for m in msgs:
        if (m.name == "MANUAL_CONTROL" or m.name == "HEARTBEAT"): # skip manual control and heartbeat; manual control should be first and heartbeat last.
            continue        
        t.write(
            outf,
            '''
        mavlink.${cleanname}_id:
            if(checkCrc(mavlink.${cleanname}_crcx, @packet))
                hdl_${cleanname}(@packet)
            else
                crcError()
''',
                {
                    "classname": m.classname,
                    "field_names": ", ".join(m.spin_names),
                    "docstring": wrapper.fill(m.description.strip()),
                    "cleanname": m.cleanname,
                    "crc_extra": m.crc_extra,
                    "msgid": m.id,
                    "spin_fields": ", ".join(m.spin_fields),
                    "init_fields": "\n    ".join(m.init_fields),
                },
        )
    t.write(
        outf,
        '''
        mavlink.MSG_ID_HEARTBEAT:
            hdl_heartbeat(@packet)
        
''') 
def generate_handler(outf, msgs):
    wrapper = textwrap.TextWrapper(initial_indent="", subsequent_indent="    ")
    for m in msgs:        
        t.write(
            outf,
'''{{${name}(${msgid})
${spin_fields}
}}
PUB hdl_${cleanname}(^mavlink.MAVLink packet) | mavlink.${classname} msg
    BYTEMOVE(@msg, @packet.payload, sizeof(msg))
    ' TODO: implement handler
                
''',
                {
                    "name": m.name.upper(),
                    "classname": m.classname,
                    "field_names": ", ".join(m.spin_names),
                    "docstring": wrapper.fill(m.description.strip()),
                    "cleanname": m.cleanname,
                    "crc_extra": m.crc_extra,
                    "msgid": m.id,
                    "spin_fields": ", ".join(m.spin_fields),
                    "init_fields": "\n    ".join(m.init_fields),
                },
        )


def generate(basename, xml):
    """generate complete spin2 implementation"""
    if basename.endswith(".spin2"):
        filename = basename
    else:
        filename = basename + ".spin2"
    
    msgs = []
    enums = []
    filelist = []
    for x in xml:
        msgs.extend(x.message)
        enums.extend(x.enum)
        filelist.append(os.path.basename(x.filename))

    for m in msgs:
        m.fielddefaults = []
        m.fmtstr = "<"
        m.native_fmtstr = m.fmtstr
        m.instance_field = None
        
        for f in m.ordered_fields:
            m.fmtstr += mavfmt(f)
            m.fielddefaults.append(mavdefault(f))
            m.native_fmtstr += native_mavfmt(f)
            if f.instance:
                m.instance_field = f.name
        m.order_map = [0] * len(m.fieldnames)
        m.len_map = [0] * len(m.fieldnames)
        m.array_len_map = [0] * len(m.fieldnames)
        for i in range(0, len(m.fieldnames)):
            m.order_map[i] = m.ordered_fieldnames.index(m.fieldnames[i])
            m.array_len_map[i] = m.ordered_fields[i].array_length
        for i in range(0, len(m.fieldnames)):
            n = m.order_map[i]
            m.len_map[n] = m.fieldlengths[i]

    print("Generating %s" % filename)
    outf = open(filename, "w", encoding='utf-8')
    dialect = xml[0].filename
    dialect = dialect[dialect.rindex("/")+1:-4]  # remove .xml; we don't use os.sep here it's jank
    xml = xml[0].__dict__
    generate_preamble(outf, msgs, basename, filelist, xml)
    generate_message_ids(outf, msgs)
    generate_message_defs(outf, msgs, enums)
    generate_mavlink_parser(outf, msgs, xml)    
    # generate_methods(outf, msgs) we don't need to generate methods yet. Future.
    outf.close()
    print("Generated %s OK" % filename)
    # generates a handler skeleton
    handlername = filename[:-6] + "_handler.spin2"
    outf = open(handlername, "w", encoding='utf-8')   
    generate_case(outf, msgs, dialect)
    generate_handler(outf, msgs)
