#!/usr/bin/env python3
"""Generate mav_cmd_helpers.h — per-MAV_CMD range-check tables and helpers.

Outputs a header with:
  - param_bounds[]     explicit min/max from XML minValue/maxValue attributes
  - cmd_flags_table[]  hasLocation and isDestination flags from XML
  - Helper functions: is_float_param_invalid, lat_in_range, lon_in_range,
                      cmd_flags, has_location, is_destination, check_range

All commands with bounds or flags defined in the XML are included in the tables.
"""

import argparse
import math
import os
import sys

# Allow package-relative imports when invoked as a script.
# The grandparent of this file is the directory that contains the
# "pymavlink" package (e.g. the repo root or site-packages parent).
if __name__ == "__main__" and __package__ is None:
    _here = os.path.dirname(os.path.abspath(__file__))          # generator/
    _pymavlink = os.path.dirname(_here)                          # pymavlink/
    _root = os.path.dirname(_pymavlink)                          # <root>/
    if _root not in sys.path:
        sys.path.insert(0, _root)

from pymavlink.generator import mavparse


def load_with_includes(xml_path):
    """Parse xml_path and all transitively included files, merge enums into root."""
    base = os.path.dirname(os.path.abspath(xml_path))
    root = mavparse.MAVXML(xml_path, wire_protocol_version=mavparse.PROTOCOL_2_0)
    all_xml = [root]
    seen = {os.path.abspath(xml_path)}
    queue = [os.path.join(base, f) for f in root.include]
    while queue:
        path = os.path.abspath(queue.pop(0))
        if path in seen:
            continue
        seen.add(path)
        try:
            x = mavparse.MAVXML(path, wire_protocol_version=mavparse.PROTOCOL_2_0)
            all_xml.append(x)
            queue += [os.path.join(os.path.dirname(path), f) for f in x.include]
        except Exception:
            pass
    mavparse.merge_enums(all_xml)
    return root


def float_c(v):
    """Format a Python float as a C float literal, using NAN for nan values."""
    if math.isnan(v):
        return "(float)NAN"
    s = repr(float(v))
    # Ensure there's always a decimal point for clarity
    if "." not in s and "e" not in s:
        s += ".0"
    return s + "f"


def generate(xml_path, output_path):
    root = load_with_includes(xml_path)

    mav_cmd = next((e for e in root.enum if e.name == "MAV_CMD"), None)
    if mav_cmd is None:
        # This dialect (and its includes) defines no MAV_CMD enum, so there is
        # nothing to range-check. Skip generating the header rather than failing
        # the whole mavgen run.
        return False

    # Collect all MAV_CMD entries, sorted by cmd value, excluding marker entries:
    # the synthetic MAV_CMD_ENUM_END (end_marker) and the *_LAST NOP entries that only
    # mark the upper bound of a command group. Neither is a real, sendable command, so
    # neither belongs in the validation tables.
    def _is_marker(e):
        return e.end_marker or e.name.endswith("_LAST")

    entries = sorted((e for e in mav_cmd.entry if not _is_marker(e)),
                     key=lambda e: int(e.value))

    # Build param bounds table — only params with at least one bound defined
    bounds = []  # list of (cmd, param_1based, lo_float, hi_float)
    for entry in entries:
        cmd = int(entry.value)
        for param in entry.param:
            if param.reserved:
                continue
            lo_s = (param.minValue or "").strip()
            hi_s = (param.maxValue or "").strip()
            if lo_s or hi_s:
                lo = float(lo_s) if lo_s else float("nan")
                hi = float(hi_s) if hi_s else float("nan")
                bounds.append((cmd, int(param.index), lo, hi))

    # Build cmd flags table
    flags = []  # list of (cmd, flags_byte, short_name)
    for entry in entries:
        cmd = int(entry.value)
        f = 0
        if getattr(entry, "has_location", False):
            f |= 1  # CMD_FLAG_HAS_LOCATION
        if getattr(entry, "is_destination", False):
            f |= 2  # CMD_FLAG_IS_DESTINATION
        short = entry.name.replace("MAV_CMD_", "")
        flags.append((cmd, f, short))

    with open(output_path, "w") as out:
        _write(out, bounds, flags, os.path.basename(xml_path))

    return True


_HEADER_TOP = """\
/* AUTO-GENERATED by mavgen (mavgen_c_cmd_helpers.py) from {xml} — do not edit.
 * Regenerate with mavgen whenever the MAVLink XML definitions change.
 */
#pragma once

#include <math.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {{
#endif

/**
 * @brief Tests if a float command parameter is set to an invalid/default value (NaN or ±0.0).
 *
 * NaN and ±0.0 are commonly used as "not in use" defaults for float parameters.
 * Define MAV_CMD_STRICT_NAN_INVALID to reject ±0.0 and require NaN only.
 *
 * This is for the float-encoded params (p1–p4, p7, and COMMAND_LONG p5/p6). For the
 * int32 (degE7) coordinate fields of COMMAND_INT / MISSION_ITEM_INT, use coord_invalid_int().
 *
 * @param param_val  Parameter value to test.
 * @return Non-zero if param_val is invalid, zero otherwise.
 */
static inline int param_invalid(float param_val)
{{
\tuint32_t bits;
\tmemcpy(&bits, &param_val, sizeof(bits));
\tif ((bits & 0x7F800000u) == 0x7F800000u) return 1; /* NaN — always invalid */
#ifndef MAV_CMD_STRICT_NAN_INVALID
\tif (!(bits & 0x7FFFFFFFu)) return 1;                /* ±0.0 — invalid by default */
#endif
\treturn 0;
}}

/**
 * @brief Tests if an int32 (degE7) coordinate is set to the "use current position" sentinel.
 *
 * COMMAND_INT / MISSION_ITEM_INT use INT32_MAX in the x/y (lat/lon) fields to mean
 * "use the current position".
 *
 * @param coord  Coordinate value (latitude or longitude), int32 degrees × 1e7.
 * @return Non-zero if coord is the INT32_MAX sentinel, zero otherwise.
 */
static inline int coord_invalid_int(int32_t coord)
{{
\treturn coord == INT32_MAX;
}}

/**
 * @brief Tests if lat is a valid latitude, COMMAND_INT / MISSION_ITEM_INT encoding (int32 degE7).
 *
 * @param lat  Latitude, int32 degrees × 1e7 (range ±9×10⁸ for ±90°).
 * @return 1 if in range, 0 if out of range.
 */
static inline int lat_in_range_int(int32_t lat)
{{
\treturn lat >= -900000000 && lat <= 900000000;
}}

/**
 * @brief Tests if lat is a valid latitude, COMMAND_LONG encoding (float degrees).
 *
 * @param lat  Latitude in float degrees (range ±90).
 * @return 1 if in range, 0 if out of range or NaN.
 */
static inline int lat_in_range_float(float lat)
{{
\treturn lat >= -90.0f && lat <= 90.0f;
}}

/**
 * @brief Tests if lon is a valid longitude, COMMAND_INT / MISSION_ITEM_INT encoding (int32 degE7).
 *
 * @param lon  Longitude, int32 degrees × 1e7 (range ±1.8×10⁹ for ±180°).
 * @return 1 if in range, 0 if out of range.
 */
static inline int lon_in_range_int(int32_t lon)
{{
\treturn lon >= -1800000000 && lon <= 1800000000;
}}

/**
 * @brief Tests if lon is a valid longitude, COMMAND_LONG encoding (float degrees).
 *
 * @param lon  Longitude in float degrees (range ±180).
 * @return 1 if in range, 0 if out of range or NaN.
 */
static inline int lon_in_range_float(float lon)
{{
\treturn lon >= -180.0f && lon <= 180.0f;
}}

"""

_TABLES_MID = """\

/* Per-command attribute flags from XML hasLocation / isDestination. */
struct CmdFlags {{ uint16_t cmd; uint8_t flags; }};

#define CMD_FLAG_HAS_LOCATION   (1u << 0u)
#define CMD_FLAG_IS_DESTINATION (1u << 1u)

"""

_HEADER_BOTTOM = """\

/**
 * @brief Binary-search lookup for per-command attribute flags.
 *
 * @param cmd MAV_CMD command ID.
 * @return Flags byte (CMD_FLAG_HAS_LOCATION | CMD_FLAG_IS_DESTINATION), or -1 if unknown.
 */
static inline int cmd_flags(uint16_t cmd)
{{
\tunsigned lo = 0u, hi = cmd_flags_count;
\twhile (lo < hi) {{
\t\tunsigned mid = lo + (hi - lo) / 2u;
\t\tif      (cmd_flags_table[mid].cmd == cmd) return (int)cmd_flags_table[mid].flags;
\t\telse if (cmd_flags_table[mid].cmd <  cmd) lo = mid + 1u;
\t\telse                                       hi = mid;
\t}}
\treturn -1;
}}

/**
 * @brief Test if a command carries lat/lon/alt.
 *
 * @param cmd MAV_CMD command ID.
 * @return 1 if the command has location, 0 if not, -1 if unknown.
 */
static inline int has_location(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_HAS_LOCATION) != 0);
}}

/**
 * @brief Test if a command is a waypoint destination.
 *
 * @param cmd MAV_CMD command ID.
 * @return 1 if the command is a destination, 0 if not, -1 if unknown.
 */
static inline int is_destination(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_IS_DESTINATION) != 0);
}}

/* Internal: non-zero if v is a finite value (not NaN / ±Inf). Bit-manipulation avoids isnan(). */
static inline int _is_finite(float v)
{{
\tuint32_t bits;
\tmemcpy(&bits, &v, sizeof(bits));
\treturn (bits & 0x7F800000u) != 0x7F800000u;
}}

/**
 * @brief Validate MAVLink command parameters against XML-defined bounds.
 *
 * NaN/Inf params are treated as "not set" and skipped. A literal 0 IS range-checked,
 * so a param whose XML minimum is greater than 0 will reject 0 (we prefer a false
 * positive here — ranges can be relaxed later — over letting a bad value through).
 *
 * @param cmd            MAV_CMD command ID.
 * @param p1,p2,p3,p4,p5,p6,p7  Command parameters 1–7.
 * @return 0 if every bounded param is in range or unset; otherwise 1–7, the 1-based
 *         index of the first failing parameter.
 */
static inline int check_range(uint16_t cmd,
\tfloat p1, float p2, float p3, float p4,
\tfloat p5, float p6, float p7)
{{
\tconst float params[7] = {{p1, p2, p3, p4, p5, p6, p7}};

\t/* Binary search: find any entry for this cmd in param_bounds. */
\tunsigned lo = 0u, hi = param_bounds_count;
\twhile (lo < hi) {{
\t\tconst unsigned mid = lo + (hi - lo) / 2u;
\t\tif      (param_bounds[mid].cmd < cmd) {{ lo = mid + 1u; continue; }}
\t\telse if (param_bounds[mid].cmd > cmd) {{ hi = mid;      continue; }}
\t\t/* Found.  Back up to first entry for this cmd. */
\t\tunsigned start = mid;
\t\twhile (start > 0u && param_bounds[start - 1u].cmd == cmd) {{ --start; }}
\t\t/* Walk all entries for this cmd. */
\t\tfor (unsigned i = start;
\t\t     i < param_bounds_count && param_bounds[i].cmd == cmd; ++i) {{
\t\t\tconst unsigned pidx = (unsigned)param_bounds[i].param - 1u;
\t\t\tconst float param_val = params[pidx];
\t\t\t/* Skip NaN/Inf "not set" params; a real 0 IS range-checked below. */
\t\t\tif (!_is_finite(param_val)) {{ continue; }}
\t\t\tif (_is_finite(param_bounds[i].lo) && param_val < param_bounds[i].lo)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t\tif (_is_finite(param_bounds[i].hi) && param_val > param_bounds[i].hi)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t}}
\t\tbreak;
\t}}

\treturn 0;
}}

#ifdef __cplusplus
}} /* extern "C" */
#endif
"""


def _write(out, bounds, flags, basename):
    out.write(_HEADER_TOP.format(xml="%s and its includes" % basename))

    # --- param_bounds table ---
    out.write("/* Explicit param bounds from XML minValue / maxValue.\n"
              " * (float)NAN for lo or hi means that side is unbounded. */\n")
    out.write("struct ParamBound { uint16_t cmd; uint8_t param; float lo; float hi; };\n\n")
    out.write("static const struct ParamBound param_bounds[] = {\n")
    for cmd, pidx, lo, hi in bounds:
        out.write(
            "\t{{ {:5d}, {:d}, {:>14s}, {:>14s} }},\n".format(
                cmd, pidx, float_c(lo), float_c(hi)
            )
        )
    out.write("};\n")
    out.write("static const unsigned param_bounds_count =\n"
              "\tsizeof(param_bounds) / sizeof(param_bounds[0]);\n")

    out.write(_TABLES_MID.format())

    # --- cmd_flags_table ---
    out.write("static const struct CmdFlags cmd_flags_table[] = {\n")
    for cmd, f, short in flags:
        parts = []
        if f & 1:
            parts.append("CMD_FLAG_HAS_LOCATION")
        if f & 2:
            parts.append("CMD_FLAG_IS_DESTINATION")
        flag_str = " | ".join(parts) if parts else "0"
        out.write("\t{{ {:5d}, {:s} }}, /* {:s} */\n".format(cmd, flag_str, short))
    out.write("};\n")
    out.write("static const unsigned cmd_flags_count =\n"
              "\tsizeof(cmd_flags_table) / sizeof(cmd_flags_table[0]);\n")

    out.write(_HEADER_BOTTOM.format())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate MAVLink command range-check helper tables"
    )
    parser.add_argument("xml", help="Root MAVLink XML dialect file (e.g. common.xml)")
    parser.add_argument("--output", required=True, help="Output .h file path")
    args = parser.parse_args()
    if generate(args.xml, args.output):
        print("Generated", args.output)
    else:
        print("Skipped %s: no MAV_CMD enum in %s" % (args.output, args.xml))
