#!/usr/bin/env python3
"""Generate mav_cmd_helpers.h — per-MAV_CMD range-check tables and helpers.

Outputs a header with:
  - param_bounds[]     explicit min/max from XML minValue/maxValue attributes
  - cmd_flags_table[]  hasLocation and isDestination flags from XML
  - Helper functions: is_float_param_invalid, lat_in_range, lon_in_range,
                      cmd_flags, has_location, is_destination, check_range

All commands with bounds or flags defined in the XML are included in the tables.
"""

import argparse
import math
import os
import sys

# Allow package-relative imports when invoked as a script.
# The grandparent of this file is the directory that contains the
# "pymavlink" package (e.g. the repo root or site-packages parent).
if __name__ == "__main__" and __package__ is None:
    _here = os.path.dirname(os.path.abspath(__file__))          # generator/
    _pymavlink = os.path.dirname(_here)                          # pymavlink/
    _root = os.path.dirname(_pymavlink)                          # <root>/
    if _root not in sys.path:
        sys.path.insert(0, _root)

from pymavlink.generator import mavparse


def load_with_includes(xml_path):
    """Parse xml_path and all transitively included files, merge enums into root."""
    base = os.path.dirname(os.path.abspath(xml_path))
    root = mavparse.MAVXML(xml_path, wire_protocol_version=mavparse.PROTOCOL_2_0)
    all_xml = [root]
    seen = {os.path.abspath(xml_path)}
    queue = [os.path.join(base, f) for f in root.include]
    while queue:
        path = os.path.abspath(queue.pop(0))
        if path in seen:
            continue
        seen.add(path)
        try:
            x = mavparse.MAVXML(path, wire_protocol_version=mavparse.PROTOCOL_2_0)
            all_xml.append(x)
            queue += [os.path.join(os.path.dirname(path), f) for f in x.include]
        except Exception:
            pass
    mavparse.merge_enums(all_xml)
    return root


def float_c(v):
    """Format a Python float as a C float literal, using NAN for nan values."""
    if math.isnan(v):
        return "(float)NAN"
    s = repr(float(v))
    # Ensure there's always a decimal point for clarity
    if "." not in s and "e" not in s:
        s += ".0"
    return s + "f"


def generate(xml_path, output_path):
    root = load_with_includes(xml_path)

    mav_cmd = next((e for e in root.enum if e.name == "MAV_CMD"), None)
    if mav_cmd is None:
        raise RuntimeError("MAV_CMD enum not found in %s" % xml_path)

    # Collect all MAV_CMD entries, sorted by cmd value
    entries = sorted(mav_cmd.entry, key=lambda e: int(e.value))

    # Build param bounds table — only params with at least one bound defined
    bounds = []  # list of (cmd, param_1based, lo_float, hi_float)
    for entry in entries:
        cmd = int(entry.value)
        for param in entry.param:
            if param.reserved:
                continue
            lo_s = (param.minValue or "").strip()
            hi_s = (param.maxValue or "").strip()
            if lo_s or hi_s:
                lo = float(lo_s) if lo_s else float("nan")
                hi = float(hi_s) if hi_s else float("nan")
                bounds.append((cmd, int(param.index), lo, hi))

    # Build cmd flags table
    flags = []  # list of (cmd, flags_byte, short_name)
    for entry in entries:
        cmd = int(entry.value)
        f = 0
        if getattr(entry, "has_location", False):
            f |= 1  # CMD_FLAG_HAS_LOCATION
        if getattr(entry, "is_destination", False):
            f |= 2  # CMD_FLAG_IS_DESTINATION
        short = entry.name.replace("MAV_CMD_", "")
        flags.append((cmd, f, short))

    with open(output_path, "w") as out:
        _write(out, bounds, flags)


_HEADER_TOP = """\
/* AUTO-GENERATED by mavgen_cmd_helpers.py from {xml} — do not edit.
 * Regenerated by the build system when the mavlink submodule or XML changes.
 */
#pragma once

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
namespace mav_cmd_helpers {{
#endif

/**
 * @brief Tests if a parameter value is set to an invalid/default value (NaN, possibly 0, or INT32_MAX-derived).
 *
 * Returns non-zero if param_val is NaN or ±0.0, which are commonly used default values
 * for float parameters that are not in use.
 * When is_int is true (COMMAND_INT / MISSION_ITEM_INT encoding), also treats values with
 * magnitude ≥ 2.0×10⁹ as invalid; INT32_MAX (≈ 2.15×10⁹) is used in p5/p6 to mean
 * "use current position". The threshold is set below INT32_MAX but above the maximum
 * valid coordinate (±1.8×10⁹).
 *
 * Define MAV_CMD_STRICT_NAN_INVALID to reject ±0.0 and require NaN only.
 *
 * @param param_val  Parameter value to test.
 * @param is_int     True for COMMAND_INT / MISSION_ITEM_INT encoding (activates INT32_MAX check).
 * @return Non-zero if param_val is invalid, zero otherwise.
 */
static inline int param_invalid(float param_val, bool is_int)
{{
\tuint32_t bits;
\t__builtin_memcpy(&bits, &param_val, sizeof(bits));
\tif ((bits & 0x7F800000u) == 0x7F800000u) return 1; /* NaN — always invalid */
#ifndef MAV_CMD_STRICT_NAN_INVALID
\tif (!(bits & 0x7FFFFFFFu)) return 1;                /* ±0.0 — invalid by default */
#endif
\tif (is_int && (param_val >= 2.0e9f || param_val <= -2.0e9f)) return 1; /* INT32_MAX — invalid */
\treturn 0;
}}

/**
 * @brief Tests if lat is in range for a latitude.
 *
 * @param lat    Latitude to test.
 * @param is_int True for COMMAND_INT / MISSION_ITEM_INT (int32 × 1e7, range ±9×10⁸);
 *               false for COMMAND_LONG (float degrees, range ±90).
 * @return 1 if in range, 0 if out of range or NaN.
 */
static inline int lat_in_range(float lat, bool is_int)
{{
\treturn is_int ? (lat >= -9e8f   && lat <= 9e8f)
\t             : (lat >= -90.0f  && lat <= 90.0f);
}}

/**
 * @brief Tests if lon is in range for a longitude.
 *
 * @param lon    Longitude to test.
 * @param is_int True for COMMAND_INT / MISSION_ITEM_INT (int32 × 1e7, range ±1.8×10⁹);
 *               false for COMMAND_LONG (float degrees, range ±180).
 * @return 1 if in range, 0 if out of range or NaN.
 */
static inline int lon_in_range(float lon, bool is_int)
{{
\treturn is_int ? (lon >= -1.8e9f  && lon <= 1.8e9f)
\t             : (lon >= -180.0f  && lon <= 180.0f);
}}

"""

_TABLES_MID = """\

/* Per-command attribute flags from XML hasLocation / isDestination. */
struct CmdFlags {{ uint16_t cmd; uint8_t flags; }};

#define CMD_FLAG_HAS_LOCATION   (1u << 0u)
#define CMD_FLAG_IS_DESTINATION (1u << 1u)

"""

_HEADER_BOTTOM = """\

/**
 * @brief Binary-search lookup for per-command attribute flags.
 *
 * @param cmd MAV_CMD command ID.
 * @return Flags byte (CMD_FLAG_HAS_LOCATION | CMD_FLAG_IS_DESTINATION), or -1 if unknown.
 */
static inline int cmd_flags(uint16_t cmd)
{{
\tunsigned lo = 0u, hi = cmd_flags_count;
\twhile (lo < hi) {{
\t\tunsigned mid = lo + (hi - lo) / 2u;
\t\tif      (cmd_flags_table[mid].cmd == cmd) return (int)cmd_flags_table[mid].flags;
\t\telse if (cmd_flags_table[mid].cmd <  cmd) lo = mid + 1u;
\t\telse                                       hi = mid;
\t}}
\treturn -1;
}}

/**
 * @brief Test if a command carries lat/lon/alt.
 *
 * @param cmd MAV_CMD command ID.
 * @return 1 if the command has location, 0 if not, -1 if unknown.
 */
static inline int has_location(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_HAS_LOCATION) != 0);
}}

/**
 * @brief Test if a command is a waypoint destination.
 *
 * @param cmd MAV_CMD command ID.
 * @return 1 if the command is a destination, 0 if not, -1 if unknown.
 */
static inline int is_destination(uint16_t cmd)
{{
\tconst int f = cmd_flags(cmd);
\treturn f < 0 ? -1 : ((f & (int)CMD_FLAG_IS_DESTINATION) != 0);
}}

/* Internal: non-zero if bound is a finite value (not NaN / ±Inf). Bit-manipulation avoids isnan(). */
static inline int _bound_is_set(float bound)
{{
\tuint32_t bits;
\t__builtin_memcpy(&bits, &bound, sizeof(bits));
\treturn (bits & 0x7F800000u) != 0x7F800000u;
}}

/**
 * @brief Validate MAVLink command parameters against XML-defined bounds.
 *
 * @param cmd            MAV_CMD command ID.
 * @param p1,p2,p3,p4,p5,p6,p7  Command parameters 1–7.
 * @return 0 if all params are in range or param_invalid values (e.g. NaN); 1–7 (1-based index of
 *         the first failing parameter) otherwise.
 */
static inline int check_range(uint16_t cmd,
\tfloat p1, float p2, float p3, float p4,
\tfloat p5, float p6, float p7)
{{
\tconst float params[7] = {{p1, p2, p3, p4, p5, p6, p7}};

\t/* Binary search: find any entry for this cmd in param_bounds. */
\tunsigned lo = 0u, hi = param_bounds_count;
\twhile (lo < hi) {{
\t\tconst unsigned mid = lo + (hi - lo) / 2u;
\t\tif      (param_bounds[mid].cmd < cmd) {{ lo = mid + 1u; continue; }}
\t\telse if (param_bounds[mid].cmd > cmd) {{ hi = mid;      continue; }}
\t\t/* Found.  Back up to first entry for this cmd. */
\t\tunsigned start = mid;
\t\twhile (start > 0u && param_bounds[start - 1u].cmd == cmd) {{ --start; }}
\t\t/* Walk all entries for this cmd. */
\t\tfor (unsigned i = start;
\t\t     i < param_bounds_count && param_bounds[i].cmd == cmd; ++i) {{
\t\t\tconst unsigned pidx = (unsigned)param_bounds[i].param - 1u;
\t\t\tconst float param_val = params[pidx];
\t\t\tif (param_invalid(param_val, false)) {{ continue; }}
\t\t\tif (_bound_is_set(param_bounds[i].lo) && param_val < param_bounds[i].lo)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t\tif (_bound_is_set(param_bounds[i].hi) && param_val > param_bounds[i].hi)
\t\t\t\t{{ return (int)param_bounds[i].param; }}
\t\t}}
\t\tbreak;
\t}}

\treturn 0;
}}

#ifdef __cplusplus
}} /* namespace mav_cmd_helpers */
#endif
"""


def _write(out, bounds, flags):
    # We need the xml basename for the comment; use a placeholder resolved at call time.
    # Instead, just use a generic note.
    out.write(_HEADER_TOP.format(xml="common.xml (via dialect include chain)"))

    # --- param_bounds table ---
    out.write("/* Explicit param bounds from XML minValue / maxValue.\n"
              " * (float)NAN for lo or hi means that side is unbounded. */\n")
    out.write("struct ParamBound { uint16_t cmd; uint8_t param; float lo; float hi; };\n\n")
    out.write("static const struct ParamBound param_bounds[] = {\n")
    for cmd, pidx, lo, hi in bounds:
        out.write(
            "\t{{ {:5d}, {:d}, {:>14s}, {:>14s} }},\n".format(
                cmd, pidx, float_c(lo), float_c(hi)
            )
        )
    out.write("};\n")
    out.write("static const unsigned param_bounds_count =\n"
              "\tsizeof(param_bounds) / sizeof(param_bounds[0]);\n")

    out.write(_TABLES_MID.format())

    # --- cmd_flags_table ---
    out.write("static const struct CmdFlags cmd_flags_table[] = {\n")
    for cmd, f, short in flags:
        parts = []
        if f & 1:
            parts.append("CMD_FLAG_HAS_LOCATION")
        if f & 2:
            parts.append("CMD_FLAG_IS_DESTINATION")
        flag_str = " | ".join(parts) if parts else "0"
        out.write("\t{{ {:5d}, {:s} }}, /* {:s} */\n".format(cmd, flag_str, short))
    out.write("};\n")
    out.write("static const unsigned cmd_flags_count =\n"
              "\tsizeof(cmd_flags_table) / sizeof(cmd_flags_table[0]);\n")

    out.write(_HEADER_BOTTOM.format())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate MAVLink command range-check helper tables"
    )
    parser.add_argument("xml", help="Root MAVLink XML dialect file (e.g. common.xml)")
    parser.add_argument("--output", required=True, help="Output .h file path")
    args = parser.parse_args()
    generate(args.xml, args.output)
    print("Generated", args.output)
