language: python
python:
  - "2.7.12"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  # --exit-zero means that flake8 will only warn and not stop the build
  # 127 characters is the width of a GitHub editor
# E401 multiple imports on one line
# E402 module level import not at top of file
# E502 the backslash is redundant between brackets
# E701 multiple statements on one line (colon)
# E703 statement ends with a semicolon
# E711 comparison to None should be 'if cond is not None:'
# E712 comparison to False should be 'if cond is False:' or 'if not cond:'
# E713 test for membership should be 'not in'
# E731 do not assign a lambda expression, use a def
# E999 SyntaxError: invalid syntax
# F401 'time' imported but unused
# F403 'from math import *' used; unable to detect undefined names
# F405 log may be undefined, or defined from star imports: math
# F811 redefinition of unused 'radians' from line 26
# F821 undefined name 'filename'
# F841 local variable 'e' is assigned to but never used
# W191 indentation contains tabs
  flake8 . --count --exit-zero --max-line-length=127 --select=E401,E402,E502,E701,E703,E711,E712,E713,E731,E999,F401,F403,F405,F811 ,F821,F841,W191 --statistics 

script:
  # NOTE: we must do all testing on the installed python package, not 
  # on the build tree. Otherwise the testing is invalid and may not
  # indicate the code actually works
  #
  # Set pythonpath

  # install
  - git clone git://github.com/mavlink/mavlink.git
  - ln -s $PWD/mavlink/message_definitions ../
  - python setup.py build install

  # Generate messages
  - mavgen.py --lang='Python' 	--output=/tmp/ mavlink/message_definitions/v1.0/common.xml
  - mavgen.py --lang='C' 	--output=/tmp/ mavlink/message_definitions/v1.0/common.xml
  - mavgen.py --lang='CS' 	--output=/tmp/ mavlink/message_definitions/v1.0/common.xml
  - mavgen.py --lang='WLua' 	--output=/tmp/ mavlink/message_definitions/v1.0/common.xml
  - mavgen.py --lang='Java'	--output=/tmp/ mavlink/message_definitions/v1.0/common.xml
  # Avoid `spurious errors` caused by ~/.npm permission issues
  # ref: https://github.com/travis-ci/travis-ci/issues/2244
  # ref: https://github.com/npm/npm/issues/4815
  # Does it already exist? Who owns? What permissions?
  - ls -lah ~/.npm || mkdir ~/.npm
  # Make sure we own it
  # $USER references the current user in Travis env
  - sudo chown -R $USER ~/.npm
  - "cd generator/javascript && npm test"

  # Test quaternions
  - cd $TRAVIS_BUILD_DIR
  - tools/quaterniontest.py
