/// <Remark>
/// AUTO-GENERATED FILE.  DO NOT MODIFY.
/// 
/// This class was automatically generated by the
/// C# mavlink generator tool. It should not be modified by hand.
/// </Remark>
using System;

namespace MavLinkProtocol
{
    /// <summary>
    ///     Description attribute for use of the field and message descriptions.
    /// </summary>
    public class Description : Attribute
    {
        public Description(string desc)
        {
            Text = desc;
        }

        public string Text { get; set; }
    }

    /// <summary>
    ///     Units attribute for defining the units of certain fields.
    /// </summary>
    public class Units : Attribute
    {
        public Units(string unit)
        {
            Unit = unit;
        }

        public string Unit { get; set; }
    }
}
