/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink;

import java.nio.ByteBuffer;

/**
 * MAVLink signature for MAVLink packets. This allows signing of MAVLink packets to ensure they are not tampered with
 *
 * Signature structure:
 *
 *      0                                                           1
 *      0     1     2     3     4     5     6     7     8     9     0     1     2
 * +-------+-----------------------------------+-------------------------------------+
 * |linkid |             timestamp             |      last 6 bytes of SHA256 hash    |
 * +-------+-----------------------------------+-------------------------------------+
 *  1 byte                6 bytes                               6 bytes
 *
 *  total 13 bytes long
 *
 * * linkid - MAVLink sysid of source
 * * timestamp - timestamp of message from source, in ms since UNIX epoch
 * * hash - last 6 bytes of SHA256 hash
 */
public class Signature {
    public static final int MAX_SIGNATURE_SIZE = 13;
    public final ByteBuffer signature;

    public Signature() {
    	signature = ByteBuffer.allocate(MAX_SIGNATURE_SIZE);
    }
}
