/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * Dart mavlink generator tool. It should not be modified by hand.
 */

import 'package:mavlink/mavlink.dart';

abstract class MAVLinkMessage {
  int sysID = 0;
  int compID = 0;
  int msgID = 0;
  bool isMavlink2 = false;

  MAVLinkMessage({required this.sysID, required this.compID, required this.msgID, bool this.isMavlink2 = false});

  MAVLinkPacket pack(int seq);
  void unpack(MAVLinkPayload payload);
  String toString();
  String getMessageName();
}
