/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * Dart mavlink generator tool. It should not be modified by hand.
 */

import 'package:mavlink/mavlink.dart';

abstract class MAVLinkMessage {
  int sysID;
  int compID;
  int msgID;
  bool isMavlink2;

  MAVLinkMessage({required this.sysID, required this.compID, required this.msgID, this.isMavlink2 = false});

  MAVLinkPacket pack(int seq);
  void unpack(MAVLinkPayload payload);
  String getMessageName();
}
